### ISSUE TITLE
parsers for 2018 General Election

### ISSUE THREAD

**Issue by rootsmusic** [openelections/openelections-data-pa#108]
Since you don't have a [validator](https://github.com/openelections/openelections-data-pa/tree/master/validators) for 2018, I'm validating [your files for 2018 General Election](https://github.com/openelections/openelections-data-pa/tree/master/2018/counties).  But I see parsers only for [Beaver](https://github.com/openelections/openelections-data-pa/blob/master/parsers/el30_parser.py), [Butler](https://github.com/openelections/openelections-data-pa/blob/master/parsers/el30a_parser.py) and [Westmoreland](https://github.com/openelections/openelections-data-pa/blob/master/parsers/el30b_parser.py).  Did you have more code to process [openelections-sources-pa](https://github.com/openelections/openelections-sources-pa/tree/master/2018/general)?  Thanks.

P.S. I think [clarity_parser.py](https://raw.githubusercontent.com/openelections/openelections-data-pa/master/parsers/clarity_parser.py) is for WV.

**Comment by dwillis** [comment]
@rootsmusic Thanks - the 2020 primaries validator checks the converted CSV files against county-level totals produced by the state. It doesn't re-process the 2020 precinct sources. Would be glad if you were to validate the 2018 CSVs against the [state totals](https://www.electionreturns.pa.gov/General/SummaryResults?ElectionID=63&ElectionType=G&IsActive=0).

**Comment by rootsmusic** [comment]
Yes @dwillis, that's what I'm planning to do.  For example, I'm validating 20181106__pa__general__beaver__precinct.csv against the [official returns](https://www.electionreturns.pa.gov/General/CountyResults?countyName=Beaver&ElectionID=63&ElectionType=G&IsActive=0).  If there's a discrepancy, then I can review the parser linked in my original post for Beaver.

But I don't see parsers for counties other than those linked in my original post.  So if those counties have discrepancies, then I won't be able to debug their parsers.

P.S. [ERStat_readme.txt](https://github.com/openelections/openelections-data-pa/blob/master/ERStat_readme.txt) and [ERStat_readmep.txt](https://github.com/openelections/openelections-data-pa/blob/master/ERStat_readmep.txt) should be moved to https://github.com/openelections/openelections-sources-pa/tree/master/2016/

**Comment by dwillis** [comment]
@rootsmusic Gotcha. In many cases we didn't write specific parsers - depending on the file, we might have dumped out the text and rearranged it or used some other process that wasn't automated. For our purposes, it's enough to know that the returns don't match and then we can dive back in.

**Comment by rootsmusic** [comment]
@dwillis I'm reconciling county-level discrepancies between two versions of official sources, which I suspect to be caused by differences in the download timestamp.  The versions are [the precinct-level election results](https://github.com/openelections/openelections-sources-pa/blob/master/2018/ERStat_2018_G(114234)_20190726.txt) versus the [Reporting Center's version](https://electionreturns.pa.gov/ReportCenter/Reports).

For Westmoreland county, you uploaded [a parser](https://github.com/openelections/openelections-data-pa/blob/master/parsers/el30b_parser.py) that created 20181106__pa__general__westmoreland__precinct.csv.  So I trust it didn't introduce any typo because manual data-entry wasn't used in your process.  For other .htm files in openelections-sources-pa, can I assume that you  used similar parsers to electronically output corresponding .csv files in openelections-data-pa?

**Comment by dwillis** [comment]
@rootsmusic that's correct - the only time data entry would have been used is if the source file in question was an image PDF. FWIW, the state's official precinct results file often has discrepancies when compared to individual county-produced files.

**Comment by rootsmusic** [comment]
Great -- saves me from some manual validation!  (By the way, my previous reply linked two versions from the same department so they should be the same if certified.)  I'm understanding that every county's BOE certifies their own results before the Department of State will certify the combined results.  After the BOE's certification, the BOE's certified results should be the same as those certified by the DOS.  The exception to certifying the same results is if the BOE were to discover an error or a court orders to include or exclude votes based on legality.
