### ISSUE TITLE
Greene County - Auditor General Candidates added as Attorney General

### ISSUE THREAD

**Issue by peter-redistricting-data-hub** [openelections/openelections-data-pa#116]
Nina Ahmad, Timothy Defoor, Jennifer Moore and Olivia Faison are all auditor general candidates mistakenly marked as attorney general candidates in a handful of precincts. 

Write-in votes for these precincts appear to be off as well

**Comment by peter-redistricting-data-hub** [comment]
This is for 2020

**Comment by dwillis** [comment]
@peter-redistricting-data-hub I've pushed a change that I think should address this issue.

**Comment by peter-redistricting-data-hub** [comment]
It seems to be corrected in the county-level file, but hasn't been pushed over to the combined [20201103__pa__general__precinct.csv](https://github.com/openelections/openelections-data-pa/blob/master/2020/20201103__pa__general__precinct.csv) file yet fyi.

**Comment by dwillis** [comment]
@peter-redistricting-data-hub right - I'll be doing that after I address the other issues you've raised.

**Comment by peter-redistricting-data-hub** [comment]
Noted, thanks!
