### ISSUE TITLE
Discrepancy in Forest County 2018 general total

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-pa#12]
In the U.S. Senate race, the state total has one more vote for Casey than the county precinct results document does. "The reason for the difference is that there was a provisional ballot that was cast and counted at the official computation," according to Jean Ann Hitchcock, Forest County's elections director.

**Comment by rootsmusic** [comment]
Yes for BOB CASEY, JR in 0004 HICKORY TWP.  Also a single vote discrepancy for Wolf (candidate for Governor).

**Comment by rootsmusic** [comment]
This issue should be corrected by #136

**Comment by rootsmusic** [comment]
@dwillis Close this issue because you completed in https://github.com/openelections/openelections-data-pa/commit/c658d0ad55ee5d7c89463e50ebc956fb5a86b3a1?

**Comment by dwillis** [comment]
thanks!
