### ISSUE TITLE
TIM HENNESSEY election results (2018 geneeral) missing in Chester County

### ISSUE THREAD

**Issue by joshuakalla** [openelections/openelections-data-pa#13]
In State House District 26, vote totals for the Republican candidate (TIM HENNESSEY) is missing for several precincts. For example, in Precinct 0060 WEST CALN 1 results are only reported for Pam Hacker and Write-Ins. I believe this is also true in the following precincts:
- 0061 WEST CALN 2
- 0301 HONEY BROOK TWP 2
- 0695 WALLACE

I am not sure if this issue exists in other state house districts or other races. I have only looked at this only race.

**Comment by dwillis** [comment]
@joshuakalla Thanks, Josh. We'll take a look (Chester results are [here](https://github.com/openelections/openelections-sources-pa/blob/master/2018/chester_2018_general.html)).

**Comment by dwillis** [comment]
@joshuakalla This issue is resolved in the file in the `counties` folder and will be part of the next build of the statewide file.
