### ISSUE TITLE
2018 General - Delaware County some lines duplicated

### ISSUE THREAD

**Issue by milandv** [openelections/openelections-data-pa#20]
May actually be the whole thing or close to, based on the totals (I didn't dig deeply enough to confirm), but here's a sample where each of the rows in SPRINGFIELD 7W 1P appear in duplicate:

Delaware,SPRINGFIELD 7W 1P,U.S. House,5,Mary Gay SCANLON,Democrat,220,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,5,Pearl KIM,Republican,284,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,5,Write In,,0,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Mary Gay SCANLON,Democrat,219,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Pearl KIM,Republican,280,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Brianna JOHNSTON,Green,1,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Sandra Teresa SALAS,Libertarian,1,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Write In,,0,,
Delaware,SPRINGFIELD 7W 1P,State Senate,26,Tim KEARNEY,Democrat,177,,
Delaware,SPRINGFIELD 7W 1P,State Senate,26,Thomas J. MCGARRIGLE SR,Republican,328,,
Delaware,SPRINGFIELD 7W 1P,State Senate,26,Write In,,1,,
Delaware,SPRINGFIELD 7W 1P,State House,165,Jennifer O'MARA,Democrat,198,,
Delaware,SPRINGFIELD 7W 1P,State House,165,Alexander T. CHARLTON,Republican,308,,
Delaware,SPRINGFIELD 7W 1P,State House,165,Write In,,0,,
Delaware,SPRINGFIELD 7W 1P,State House,165,No Vote,,0,,
Delaware,SPRINGFIELD 7W 1P,U.S. Senate,,Bob CASEY JR,Democrat,252,,
Delaware,SPRINGFIELD 7W 1P,U.S. Senate,,Lou BARLETTA,Republican,249,,
Delaware,SPRINGFIELD 7W 1P,U.S. Senate,,Neal GALE,Green,2,,
Delaware,SPRINGFIELD 7W 1P,U.S. Senate,,Dale R. KERNS JR,Libertarian,3,,
Delaware,SPRINGFIELD 7W 1P,U.S. Senate,,Write In,,0,,
Delaware,SPRINGFIELD 7W 1P,Governor,,Tom WOLF,Democrat,264,,
Delaware,SPRINGFIELD 7W 1P,Governor,,Scott R. WAGNER,Republican,235,,
Delaware,SPRINGFIELD 7W 1P,Governor,,Paul GLOVER,Green,3,,
Delaware,SPRINGFIELD 7W 1P,Governor,,Ken V. KRAWCHUK,Libertarian,2,,
Delaware,SPRINGFIELD 7W 1P,Governor,,Write In,,0,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,5,Mary Gay SCANLON,Democrat,220,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,5,Pearl KIM,Republican,284,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,5,Write In,,0,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Mary Gay SCANLON,Democrat,219,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Pearl KIM,Republican,280,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Brianna JOHNSTON,Green,1,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Sandra Teresa SALAS,Libertarian,1,,
Delaware,SPRINGFIELD 7W 1P,U.S. House,7,Write In,,0,,
Delaware,SPRINGFIELD 7W 1P,State Senate,26,Tim KEARNEY,Democrat,177,,
Delaware,SPRINGFIELD 7W 1P,State Senate,26,Thomas J. MCGARRIGLE SR,Republican,328,,
Delaware,SPRINGFIELD 7W 1P,State Senate,26,Write In,,1,,

**Comment by baxterdemers** [comment]
I ran into the same issue - until the source is fixed it can easily be addressed in python with [pandas](https://pandas.pydata.org/) like so:

```
import pandas as pd
df  = pd.read_csv('20181106__pa__general__precinct.csv')
df = df.drop_duplicates()
```
