### ISSUE TITLE
Franklin County General Election 2018 is too low

### ISSUE THREAD

**Issue by wbannick** [openelections/openelections-data-pa#24]
Franklin county 2018 general election results seem to be significantly lower than the official county results from PA's sos website.

Thank you for your time!

**Comment by dwillis** [comment]
@wbannick Looks like we're missing precincts in Franklin. Thanks, we'll fix!

**Comment by dwillis** [comment]
@wbannick We've replaced the Franklin file.

**Comment by wbannick** [comment]
Thank you!
