### ISSUE TITLE
Precinct Code?

### ISSUE THREAD

**Issue by alan-ren** [openelections/openelections-data-pa#4]
Thanks so much for all of your work in collecting and converting the raw data into this processed spreadsheet. I was wondering if you could clarify something about the Precinct Code field.

From looking at the County Code and Precinct Code fields, I can see that row 1 of `20161108__pa__general__precinct.csv` pertains to "Adams County, Precinct 10." From the County Code and Municipality Name fields, I can see that this is also referred to as "Adams County, Precinct Abbottstown." 

Would you mind clarifying where Precinct Code is derived from? It seems that you're using [Open Civic Data](https://github.com/opencivicdata/ocd-division-ids/tree/master/identifiers/country-us) precinct identifiers, such that combining Municipality Name with Municipality Breakdown Name 1 yields the full OCD precinct identifier (e.g. "Adams County, Precinct Carroll Valley 1"). However, I can't seem to find reference to the Precinct Code in the documentation for this repo (both `openelections-sources-pa` and `openelections-data-pa`) as well as in the OCD docs. 

I'm just interested in understanding whether the Precinct Code field is something that's defined by a government entity, by OCD, or by the Open Elections project, so I have a better sense of what to index/join on in this particular table. Thanks for your help and happy holidays!

**Comment by dwillis** [comment]
Hi @alan-ren: sure, happy to clarify. The Precinct Code is contained in the files we receive from the Pennsylvania Department of State, and you're right, we produce the OCD identifier using them. My understanding is that the state produces the precinct code, but it may in fact be a product of individual counties. It's definitely not something we have created.

**Comment by alan-ren** [comment]
Thanks for your prompt reply! That helps to clarify things. Hope you had a great Christmas!
