### ISSUE TITLE
Beaver County 2020 General Precinct File

### ISSUE THREAD

**Issue by kroytesir** [openelections/openelections-data-pa#76]
Independence Township Presidential Results shows:

Biden 397
Jorgenson 27

That's not right, B[eaver County Official Election Results](http://www.beavercountypa.gov/Depts/Elections/Documents/Nov2020Results/PrecinctsResults11022020.pdf) are:

Biden 401
Trump 1007
Jorgenson 27

**Comment by kroytesir** [comment]
New Sewickley TWP  in the same file is also missing Trump votes.

**Comment by kroytesir** [comment]
South Beaver TWP in the same file is also missing Trump votes.

**Comment by dwillis** [comment]
@kroytesir thanks - we will fix.
